adding testGas
chiru-labs/ERC721A pull request #19
Opened 2022-01-23 11:13 UTC by AndreiD

adding testGas & consistent " instead of '

2022-01-23 19:38 UTC, cygaar requested changes

2022-01-23 19:38 UTC, cygaar commented on contracts/ERC721A.sol
> +pragma solidity ^0.8.11;
Let's keep this at 0.8.0 to maintain maximum compatibility

2022-01-23 19:38 UTC, cygaar commented on hardhat.config.js
> -  solidity: "0.8.4",
Can you actually change this to 0.8.0? Missed this during my initial setup

2022-01-25 03:51 UTC, cygaar commented
@AndreiD yeah I misspoke, it's already been changed in the main branch

2022-01-25 03:52 UTC, cygaar commented
The contract pragma version should be changed though

2022-01-25 15:21 UTC, AndreiD commented
to what? 0.8.0? but I would remove the ^..... some security auditors don't like it

2022-01-25 15:47 UTC, cygaar commented
We want to match up with OpenZeppelin which uses ^0.8.0

2022-01-25 20:10 UTC, cygaar approved these changes

2022-01-28 20:08 UTC, cygaar commented
@AndreiD can you handle the merge conflicts, then I can merge this?

2022-01-28 20:23 UTC, AndreiD commented
why the package-lock file was there.... :( no idea.

2022-01-28 20:23 UTC, AndreiD commented
check now

2022-01-28 20:27 UTC, cygaar commented
Seems like there's still an issue - I think you can just checkout the package-lock from the main branch

2022-01-29 10:45 UTC, AndreiD commented
close this one. I'll open a new pull request

2022-01-29 10:45 UTC, closed without merging