Adding WhaleTogether
chiru-labs/ERC721A pull request #22
Opened 2022-01-24 04:10 UTC by vasinl124

2022-01-24 05:38 UTC, cygaar commented
@vasinl124 let's not put discords in here since I don't want to audit the legitimacy of them.

2022-01-24 05:38 UTC, cygaar requested changes
Remove the discord

2022-01-24 09:16 UTC, vasinl124 commented
@cygaar I've removed the discord link. sorry about that.

2022-01-25 03:50 UTC, cygaar approved these changes

2022-01-25 03:53 UTC, merged