[WIP] Rewrite delete using assembly
chiru-labs/ERC721A pull request #335
Opened 2022-06-13 07:17 UTC by cygaar

Looks to save a couple gas units

2022-06-13 20:04 UTC, Vectorized commented
All for the 8 gas. Kekw.

_<inserts_optimizoor_meme_here>_

2022-06-13 20:06 UTC, Vectorized commented on contracts/ERC721A.sol
> +            deleteTokenApproval(tokenId);
Nit: should have leading underscore for private function. For consistency.

2022-06-13 20:10 UTC, Vectorized commented on contracts/ERC721A.sol
> +            mstore(32, tokenApprovalPtr.slot)
Nit: Some people (e.g. me) prefer hexadecimal (e.g. '0x00', '0x20', '0x40') for memory addresses. The Yul docs use hex for the memory addresses.

2022-06-13 20:26 UTC, Vectorized commented
Imo, we may be able to combine the line `address approvedAddress = _tokenApprovals[tokenId];` and the delete function into a single function `_deleteAndReturnApprovedAddress`.

This way, we only need to compute the keccak256 once. 

This is optimizing for the happy (non-reverting) path, which is ok in this case.

2022-06-13 21:24 UTC, Vectorized commented
Btw, looks like the compiler does optimize out the re-computation of the keccak256 for the slot. :)

2022-06-13 22:16 UTC, Vectorized commented
I just thought of an approach that may cut down even more gas. ;) 

```solidity
/**
 * @dev Returns the variables required for approval check.
 */
function _getApproved(
    uint256 tokenId, 
    address from, 
    address msgSender
) private view returns (bool isApprovedOrOwner, uint256 approvedAddressSlot, address approvedAddress) {
    mapping(uint256 => address) storage tokenApprovalsPtr = _tokenApprovals;
    assembly {
        mstore(0, tokenId)
        mstore(32, tokenApprovalsPtr.slot)
        approvedAddressSlot := keccak256(0, 64)
        approvedAddress := sload(approvedAddressSlot)
        isApprovedOrOwner := or(eq(msgSender, from), eq(msgSender, approvedAddress))
    }
}
```

Then, we'll need the following on the `_transfer` and `_burn` functions:

```solidity 
(bool isApprovedOrOwner, uint256 approvedAddressSlot, address approvedAddress) = 
    _getApproved(tokenId, from, _msgSenderERC721A());

isApprovedOrOwner = isApprovedOrOwner || isApprovedForAll(from, _msgSenderERC721A());

if (!isApprovedOrOwner) revert TransferCallerNotOwnerNorApproved();
if (_addressToUint256(to) == 0) revert TransferToZeroAddress();

_beforeTokenTransfers(from, to, tokenId, 1);

// Clear approvals from the previous owner.
assembly {
    if approvedAddress {
        sstore(approvedAddressSlot, 0)    
    }
}
```

2022-06-14 00:04 UTC, cygaar commented
Just tested this snippet:
```
bool test;
address sender = _msgSenderERC721A();
assembly {
    test := eq(sender, from)
}
console.log('from      :', from);
console.log('msg sender:', sender);
console.log('Are they equal?', test);
```

And got this output:
```
from      : 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
msg sender: 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
Are they equal? false
```

2022-06-14 00:05 UTC, cygaar commented
I'm wondering if this is caused the by the other bits in the storage slot having dirty values

2022-06-14 00:18 UTC, cygaar commented
Looks like it is. Here's my code to mask with an address mask:
```
bool test;
uint256 mask = (1 << 160) - 1;
address sender = _msgSenderERC721A();
assembly {
    test := eq(and(sender, mask), and(from, mask))
}
console.log('from      :', address(uint160(uint256(uint160(from)) & mask)));
console.log('msg sender:', address(uint160(uint256(uint160(sender)) & mask)));
console.log('Are they equal?', test);
```

This is the result
```
from      : 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
msg sender: 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
Are they equal? true
```

2022-06-14 01:56 UTC, fulldecent requested changes
Not worth it.

If this is really to be pursued, this should please be raised in the Solidity project as a way to improve their compiler optimization step.

2022-06-14 03:51 UTC, cygaar commented
I'll look into raising the issue with the solidity compiler, but I'm going to merge this in for the time being since the actual change here is pretty straightforward and gives us some gas savings.

2022-06-14 03:53 UTC, merged

2022-06-14 04:19 UTC, fulldecent commented
If things like this are being accepted then it would probably be in-scope of this project to rewrite everything in YUL.

FYI, you can take a YUL smart contract and paste the whole thing into Solidity with a line or two of wrapper and it will compile.

2022-06-14 06:08 UTC, cygaar commented
Our project's goal is "to provide a fully compliant implementation of IERC721 with significant gas savings for minting multiple NFTs in a single transaction". The change here as well as our other snippets of assembly code are meant to improve gas efficiency which is in the project scope. In a perfect world we wouldn't need to write any assembly, but right now there are gains to be had from doing so.

I don't see why it's "probably in-scope of this project to rewrite everything in YUL", but if we find it greatly efficient to do so, then maybe we'll consider it.