Update projects.md
chiru-labs/ERC721A pull request #357
Opened 2022-07-04 18:54 UTC by metawizartDev

[Edge Of Fusion 2D](https://www.edgeoffusion.com//) | [Etherscan](https://etherscan.io/address/0xBA0B93f3ef64be8cb1b239de248d94CA3657741a#code) | [Twitter](https://twitter.com/edgeoffusion)

2022-07-06 03:57 UTC, cygaar requested changes

2022-07-06 03:57 UTC, cygaar commented on projects.md
> +[Edge Of Fusion 2D](https://www.edgeoffusion.com//) | [Etherscan](https://etherscan.io/address/0xBA0B93f3ef64be8cb1b239de248d94CA3657741a#code) | [Twitter](https://twitter.com/edgeoffusion)
Remove the trailing slash

2022-07-07 16:41 UTC, metawizartDev reviewed
hello can you check the fix

2022-07-08 02:44 UTC, Vectorized approved these changes

2022-07-08 02:45 UTC, merged