[WIP] Optimize code
chiru-labs/ERC721A pull request #59
Opened 2022-01-31 22:22 UTC by DaniPopes

Wrote up a few optimizations on the main contracts, open to feedback especially for [the unchecked blocks](https://github.com/chiru-labs/ERC721A/commit/ae1cdcff0eb73c3b5a12034664a260a60486791f) if you think that over/underflow checks are needed in those functions.

[1b32797:](https://github.com/chiru-labs/ERC721A/commit/1b32797fd57660f2463500960d89bedf9f1cf8a5) _exists(uint256 id) returns id < currentIndex, and we call it with currentIndex, which always results in it returning false.

[ae1cdcf:](https://github.com/chiru-labs/ERC721A/commit/ae1cdcff0eb73c3b5a12034664a260a60486791f) Explanations in the code comments.

[5fca737:](https://github.com/chiru-labs/ERC721A/commit/5fca737705af62cf3c04f546fc9e1a588a03e846) Initializing a variable with a 0 is more expensive than not doing so, even if both results are the same. [Source:](https://medium.com/coinmonks/gas-optimization-in-solidity-part-i-variables-9d5775e43dde) 
> uint256 value; is cheaper than uint256 value = 0;

[c23e2e0:](https://github.com/chiru-labs/ERC721A/commit/c23e2e07b41453f3f366f6b0a1edb281aa6d5c3d) All values are integers which cannot be negative, saves a few opcodes.

[ee2abe2:](https://github.com/chiru-labs/ERC721A/commit/ee2abe273c77060e25535ac99876c073f4d9df40) Previous changes applied to `ERC721AOwnersExplicit`.

[81daf25:](https://github.com/chiru-labs/ERC721A/commit/81daf257a9443d24da2aa5707ef303c09c77c664) Loading `nextOwnerToExplicitlySet` into memory saves an SLOAD opcode later on line 23.

2022-02-01 01:05 UTC, chiru-labs requested changes
Sweet stuff. Just some nits

2022-02-01 01:05 UTC, chiru-labs commented on contracts/extensions/ERC721AOwnersExplicit.sol
> +            for (uint256 i = oldNextOwnerToSet; i <= endIndex; i++) {
Seems like we don't need oldNextOwnerToSet anymore and can just use `_nextOwnerToExplicitlySet` here

2022-02-01 01:05 UTC, chiru-labs commented on contracts/extensions/ERC721AOwnersExplicit.sol
> +        // Counter or index overflow is incredibly unrealistic.
Please elaborate a bit more on this line (e.g.- "incredibly unrealistic, collection size would have to be ___")

2022-02-01 01:05 UTC, chiru-labs commented on contracts/ERC721A.sol
> +        // Counter overflow is incredibly unrealistic.
Please elaborate a bit more on this line (e.g.- "incredibly unrealistic, collection size would have to be ___")

2022-02-01 04:41 UTC, DaniPopes commented
Thanks for that! I missed that last one. Also added an unchecked block to `ownershipOf` and added a condition to prevent underflow.

2022-02-01 07:20 UTC, chiru-labs approved these changes
Awesome looks good after rebase

2022-02-02 07:41 UTC, cygaar approved these changes

2022-02-02 07:41 UTC, cygaar commented
Love this

2022-02-02 07:41 UTC, merged