Added aux for AddressData
chiru-labs/ERC721A pull request #98
Opened 2022-02-13 11:43 UTC by Vectorized

After adding the `burn` feature, the `AddressData` struct still has 64 bits of unused space.

This is free real estate. 

This PR adds an `aux` variable for the `AddressData`,   
along with `_getAux` and `_setAux` functions.

This can be used for things like number of whitelist mint slots used.

Deriving contracts can avoid the overhead of an additional SSTORE (20k+ gas) with this feature.

2022-02-13 16:54 UTC, ahbanavi approved these changes
Looks good and yes it's the perfect place for storing whitelist mints.

2022-02-16 17:04 UTC, cygaar commented
Good find

2022-02-16 17:05 UTC, cygaar requested changes
Can you add a couple unit tests to verify the behavior? Should be simple since you're just checking that the setter/getter works.

2022-02-16 22:36 UTC, cygaar commented
@Vectorized for some reason you have changes from the past 2 merged PRs in your PR. It might be worth rebasing your code on top of main instead of trying to do a merge commit. Not too sure what happened. Other than that, the PR looks good

2022-02-18 07:04 UTC, merged